AllCops:
  Exclude:
    - 'examples/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Metrics/AbcSize:
  Max: 24

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - '**/*_spec.rb'
    - 'lib/apex_charts/helper.rb'

Metrics/ClassLength:
  Max: 270

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 21

Metrics/ModuleLength:
  Max: 150

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'lib/apex_charts/prefixer.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
